###get all products
GET http://localhost:8000/products
x-access-token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJwdWJsaWNfaWQiOiJlYjgzNzgyMi1iNDljLTQ1ZDctYmZhNi04ZWE4YTRmYTc1ZmQiLCJleHAiOjE2NDg4NDY4NTJ9.hb_h3lKuQ0NniMK87IoAZAenPuWOjEwie0N68Mmd7jM


###create product
POST http://localhost:8000/products
Content-Type: application/json
x-access-token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJwdWJsaWNfaWQiOiJjNjZjN2YxMy1iYzk4LTQ3NzktYTIyMy05ZjBhNjg1MzkwMzMiLCJleHAiOjE2NDg4NTA1NDJ9.xQxZs7-HEIjHrcj1yUG6v_L0SRbjUynCNXHegRm_ibU


{
    "name": "smartphone xiaomi",
    "description": "smartphone xiaomi note 8",
    "quantity": 10,
    "sku": "7854236985"
}


### get product by id
GET http://localhost:8000/products/2

### get product by sku
GET http://localhost:8000/products/sku/4545456465


### update product
PUT http://localhost:8000/products/1
Content-Type: application/json

{
    "name": "desktop",
    "description": "desktop HP",
    "quantity": 5,
    "sku": "131321231"
}

### delete user.
DELETE http://localhost:8000/products/3


###get all orders
GET http://localhost:8000/orders


###create order
POST http://localhost:8000/orders
Content-Type: application/json

{
    "product_sku": "7854236985",
    "product_name": "smartphone xiaomi",
    "quantity": 2,
    "seller_name": "walmart",
    "seller_warehouse": "nord 122",
    "marketplace_user_name": "chris",
    "marketplace_user_adress": "south 56565"
}


### get order by id
GET http://localhost:8000/orders/1


### update order
PUT http://localhost:8000/orders/2
Content-Type: application/json

{
    "product_sku": "54545646654",
    "product_name": "tablet",
    "quantity": 2,
    "seller_name": "walmart",
    "seller_warehouse": "nord 14522",
    "marketplace_user_name": "chris",
    "marketplace_user_adress": "south 56565"
    }

###updaye only order status
PUT http://localhost:8000/orders/2
Content-Type: application/json

{
    "status": "created"
}


### delete order.
DELETE http://localhost:8000/orders/1
